vinabb_web_user_routing:
    resource: routing_user.yml
    prefix: /user
vinabb_web_ucp_default_route:
    path: /ucp
    defaults:
        _controller: vinabb.web.ucp:main
        id: 'main'
        mode: 'front'
vinabb_web_ucp_route:
    path: /ucp/{id}/{mode}
    defaults:
        _controller: vinabb.web.ucp:main
        id: 'front'
        mode: ''
    requirements:
        id: '[a-z0-9-_]*'
        mode: '([a-z0-9-_]*)(\/{0,1})'
vinabb_web_mcp_route:
    path: /mcp/{id}/{mode}
    defaults:
        _controller: vinabb.web.mcp:main
        id: 'main'
        mode: ''
    requirements:
        id: '[a-z0-9-_]*'
        mode: '([a-z0-9-_]*)(\/{0,1})'
vinabb_web_board_route:
    path: /board{slash}
    defaults:
        _controller: vinabb.web.board:main
        slash: ''
    requirements:
        slash: '(|\/)'
vinabb_web_board_routing:
    resource: routing_board.yml
    prefix: /board
vinabb_web_online_route:
    path: /online/{mode}
    defaults:
        _controller: vinabb.web.online:main
        mode: ''
    requirements:
        mode: '(|whois|lookup)(\/{0,1})'
vinabb_web_board_embed_routing:
    resource: routing_embed.yml
    prefix: /embed
vinabb_web_portal_route:
    path: /news
    defaults:
        _controller: vinabb.web.portal:index
vinabb_web_bb_route:
    path: /bb{slash}
    defaults:
        _controller: vinabb.web.bb:index
        type: ''
        slash: ''
    requirements:
        slash: '(|\/)'
vinabb_web_bb_routing:
    resource: routing_bb.yml
    prefix: /bb
