vinabb_web_board_forum_route:
    path: /forum/{seo}{forum_id}/{page}
    defaults:
        _controller: vinabb.web.board.forum:main
        seo: ''
        page: ''
    requirements:
        forum_id: '\d*'
        seo: '(|([a-zA-Z0-9-]*)(\.*))'
        page: '(|((page-)(\d+)))'
vinabb_web_board_topic_route:
    path: /f{forum_id}/topic/{seo}{topic_id}/{page}
    defaults:
        _controller: vinabb.web.board.topic:main
        forum_id: 'x'
        seo: ''
        page: ''
    requirements:
        forum_id: '(x|\d+)'
        topic_id: '\d*'
        seo: '(|([a-zA-Z0-9-]*)(\.*))'
        page: '(|((page-)(\d+)))'
