vinabb_web_user_list_route:
    path: /list
    defaults:
        _controller: vinabb.web.user:memberlist
vinabb_web_user_profile_id_route:
    path: /profile/id/{user_id}
    defaults:
        _controller: vinabb.web.user:profile
    requirements:
        user_id: '\d+'
vinabb_web_user_profile_route:
    path: /profile/{username}
    defaults:
        _controller: vinabb.web.user:profile
    requirements:
        username: '.+'
vinabb_web_user_contact_admin_route:
    path: /contact/admin
    defaults:
        _controller: vinabb.web.user:contact_admin
vinabb_web_user_email_route:
    path: /email/{type}/{id}
    defaults:
        _controller: vinabb.web.user:email
        type: 'user'
    requirements:
        type: '(user|topic)'
        id: '\d+'
vinabb_web_user_contact_route:
    path: /contact/{action}/{user_id}
    defaults:
        _controller: vinabb.web.user:contact
        action: 'jabber'
    requirements:
        user_id: '\d+'
vinabb_web_user_team_route:
    path: /team
    defaults:
        _controller: vinabb.web.user:team
vinabb_web_user_group_route:
    path: /group/{group_id}
    defaults:
        _controller: vinabb.web.user:group
    requirements:
        group_id: '\d+'
vinabb_web_user_search_route:
    path: /search
    defaults:
        _controller: vinabb.web.user:search
vinabb_web_user_livesearch_route:
    path: /search/live
    defaults:
        _controller: vinabb.web.user:livesearch
vinabb_web_user_online_route:
    path: /online/{mode}{slash}
    defaults:
        _controller: vinabb.web.user.online:main
        mode: ''
        slash: ''
    requirements:
        mode: '(|lookup)'
        slash: '(|\/)'
vinabb_web_user_online_whois_route:
    path: /online/whois/{session_id}{slash}
    defaults:
        _controller: vinabb.web.user.online:whois
        slash: ''
    requirements:
        session_id: '[a-z0-9]+'
        slash: '(|\/)'
