vinabb_web_bb_type_route:
    path: /{type}{slash}
    defaults:
        _controller: vinabb.web.bb:index
        slash: ''
    requirements:
        type: '(extensions|styles|acp-styles|languages|tools)'
        slash: '(|\/)'
vinabb_web_bb_cat_route:
    path: /{type}/{cat}{slash}
    defaults:
        _controller: vinabb.web.bb.category:main
        slash: ''
    requirements:
        type: '(extensions|styles|acp-styles|languages|tools)'
        cat: '[a-z0-9-]+'
        slash: '(|\/)'
vinabb_web_bb_item_route:
    path: /{type}/{cat}/{item}{slash}
    defaults:
        _controller: vinabb.web.bb.item:main
        slash: ''
    requirements:
        type: '(extensions|styles|acp-styles|languages|tools)'
        cat: '[a-z0-9-]+'
        item: '[a-z0-9-\.]+'
        slash: '(|\/)'
