vinabb_web_portal_cat_route:
    path: /{varname}/{page}
    defaults:
        _controller: vinabb.web.portal.category:category
        page: ''
    requirements:
        varname: '[a-z0-9-]+'
        page: '(|((page-)(\d+)))'
vinabb_web_portal_article_route:
    path: /{varname}/{seo}{article_id}
    defaults:
        _controller: vinabb.web.portal.article:article
        seo: ''
    requirements:
        varname: '[a-z0-9-]+'
        article_id: '\d+'
        seo: '(|([a-zA-Z0-9-]*)(\.*))'
