services:
    vinabb.web.embed:
        class: vinabb\web\controllers\embed
        arguments:
            - '@auth'
            - '@service_container'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
