services:
    vinabb.web.entities.forum:
        class: vinabb\web\entities\forum
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
    vinabb.web.entities.portal_category:
        class: vinabb\web\entities\portal_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.portal_article:
        class: vinabb\web\entities\portal_article
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_articles%'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.portal_comment:
        class: vinabb\web\entities\portal_comment
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_comments%'
            - '%vinabb.web.tables.portal_articles%'
    vinabb.web.entities.bb_category:
        class: vinabb\web\entities\bb_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_categories%'
    vinabb.web.entities.bb_item:
        class: vinabb\web\entities\bb_item
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_items%'
            - '%vinabb.web.tables.bb_categories%'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.entities.bb_author:
        class: vinabb\web\entities\bb_author
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.entities.page:
        class: vinabb\web\entities\page
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.pages%'
    vinabb.web.entities.menu:
        class: vinabb\web\entities\menu
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.menus%'
    vinabb.web.entities.headline:
        class: vinabb\web\entities\headline
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.headlines%'
