services:
    vinabb.web.entities.portal_category:
        class: vinabb\web\entities\portal_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.portal_article:
        class: vinabb\web\entities\portal_article
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_articles%'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.bb_category:
        class: vinabb\web\entities\bb_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_categories%'
    vinabb.web.entities.bb_item:
        class: vinabb\web\entities\bb_item
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_items%'
            - '%vinabb.web.tables.bb_categories%'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.entities.page:
        class: vinabb\web\entities\page
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.pages%'
