services:
    vinabb.web.acp.settings:
        class: vinabb\web\controllers\acp\settings
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
    vinabb.web.acp.pages:
        class: vinabb\web\controllers\acp\pages
        arguments:
            - '@cache'
            - '@vinabb.web.entities.page'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.page'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
