imports:
    - { resource: tables.yml }

services:
    # Decorates
    vinabb.web.decorated.cache:
        class: vinabb\web\decorated\cache\service
        decorates: cache
        arguments:
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%vinabb.web.tables.bb_categories%'
            - '%vinabb.web.tables.bb_items%'
            - '%vinabb.web.tables.portal_categories%'
            - '%vinabb.web.tables.portal_articles%'
            - '%vinabb.web.tables.portal_comments%'
    vinabb.web.decorated.help.controller.faq:
        class: vinabb\web\decorated\help\controller\faq
        decorates: phpbb.help.controller.faq
        arguments:
            - '@controller.helper'
            - '@phpbb.help.manager'
            - '@template'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.decorated.help.controller.bbcode:
        class: vinabb\web\decorated\help\controller\bbcode
        decorates: phpbb.help.controller.bbcode
        arguments:
            - '@controller.helper'
            - '@phpbb.help.manager'
            - '@template'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.decorated.message.form.topic:
        class: vinabb\web\decorated\message\topic_form
        decorates: message.form.topic
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.decorated.message.form.user:
        class: vinabb\web\decorated\message\user_form
        decorates: message.form.user
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.decorated.text_formatter.s9e.factory:
        class: vinabb\web\decorated\textformatter\s9e\factory
        decorates: text_formatter.s9e.factory
        arguments:
            - '@text_formatter.data_access'
            - '@cache.driver'
            - '@dispatcher'
            - '@config'
            - '@language'
            - '@text_formatter.s9e.link_helper'
            - '%text_formatter.cache.dir%'
            - '%text_formatter.cache.parser.key%'
            - '%text_formatter.cache.renderer.key%'
    vinabb.web.decorated.text_formatter.s9e.renderer:
        class: vinabb\web\decorated\textformatter\s9e\renderer
        decorates: text_formatter.s9e.renderer
        arguments:
            - '@cache.driver'
            - '%text_formatter.cache.dir%'
            - '%text_formatter.cache.renderer.key%'
            - '@text_formatter.s9e.factory'
            - '@dispatcher'
            - '@language'
        calls:
            - [configure_quote_helper, ['@text_formatter.s9e.quote_helper']]
            - [configure_smilies_path, ['@config', '@path_helper']]
            - [configure_user, ['@user', '@config', '@auth']]
    # Common classes
    vinabb.web.pagination:
        class: vinabb\web\controller\pagination
        arguments:
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
    vinabb.web.helper:
        class: vinabb\web\controller\helper
        arguments:
            - '@dbal.conn'
            - '@file_downloader'
            - '@language'
            - '@template'
            - '%vinabb.web.tables.bb_items%'
            - '%vinabb.web.tables.portal_articles%'
    # Controllers replace original phpBB front files
    vinabb.web.user:
        class: vinabb\web\controller\user
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@message.form.admin'
            - '@message.form.topic'
            - '@message.form.user'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.ucp:
        class: vinabb\web\controller\ucp
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@ext.manager'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.mcp:
        class: vinabb\web\controller\mcp
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@dispatcher'
            - '@ext.manager'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board:
        class: vinabb\web\controller\board\board
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.forum:
        class: vinabb\web\controller\board\forum
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@cron.manager'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.topic:
        class: vinabb\web\controller\board\topic
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.post:
        class: vinabb\web\controller\board\post
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@cron.manager'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@notification_manager'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.posting:
        class: vinabb\web\controller\board\posting
        arguments:
            - '@auth'
            - '@cache'
            - '@captcha.factory'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@log'
            - '@plupload'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.search:
        class: vinabb\web\controller\board\search
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.online:
        class: vinabb\web\controller\online
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
    # Embed
    vinabb.web.embed:
        class: vinabb\web\controller\embed
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    # Entities
    vinabb.web.entity.portal_category:
        class: vinabb\web\entity\portal_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entity.bb_category:
        class: vinabb\web\entity\bb_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_categories%'
    vinabb.web.entity.page:
        class: vinabb\web\entity\page
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%vinabb.web.tables.pages%'
    # Operators
    vinabb.web.operator.nestedset_portal_categories:
        class: vinabb\web\operators\nestedset_portal_categories
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.table_lock.portal_categories'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.operator.portal_category:
        class: vinabb\web\operators\portal_category
        arguments:
            - '@service_container'
            - '@vinabb.web.operator.nestedset_portal_categories'
    vinabb.web.operator.page:
        class: vinabb\web\operators\page
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.entity.page'
            - '%vinabb.web.tables.pages%'
    # Table lock
    vinabb.web.table_lock.portal_categories:
        class: phpbb\lock\db
        arguments:
            - 'vinabb.web.table_lock.%vinabb.web.tables.portal_categories%'
            - '@config'
            - '@dbal.conn'
    # Controllers
    vinabb.web.portal:
        class: vinabb\web\controller\portal\portal
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@dispatcher'
            - '@ext.manager'
            - '@language'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '@group_helper'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.portal.article:
        class: vinabb\web\controller\portal\article
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%vinabb.web.tables.portal_articles%'
            - '%vinabb.web.tables.portal_comments%'
    vinabb.web.bb:
        class: vinabb\web\controller\bb\bb
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
    # Listeners
    vinabb.web.listener:
        class: vinabb\web\event\listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@cache'
            - '@config'
            - '@ext.manager'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
