services:
    vinabb.web.portal:
        class: vinabb\web\controllers\portal\portal
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@language'
            - '@vinabb.web.pagination'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '@vinabb.web.helper.portal'
    vinabb.web.portal.article:
        class: vinabb\web\controllers\portal\article
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.php_ext%'
    vinabb.web.bb:
        class: vinabb\web\controllers\bb\bb
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
    vinabb.web.bb.category:
        class: vinabb\web\controllers\bb\category
        arguments:
            - '@vinabb.web.cache'
            - '@service_container'
            - '@language'
            - '@vinabb.web.pagination'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
