services:
    vinabb.web.operators.nestedset_portal_categories:
        class: vinabb\web\operators\nestedset_portal_categories
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.table_lock.portal_categories'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.operators.nestedset_menus:
        class: vinabb\web\operators\nestedset_menus
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.table_lock.menus'
            - '%vinabb.web.tables.menus%'
    vinabb.web.operators.portal_category:
        class: vinabb\web\operators\portal_category
        arguments:
            - '@vinabb.web.entities.portal_category'
            - '@vinabb.web.operators.nestedset_portal_categories'
    vinabb.web.operators.portal_article:
        class: vinabb\web\operators\portal_article
        arguments:
            - '@vinabb.web.entities.portal_article'
    vinabb.web.operators.portal_comment:
        class: vinabb\web\operators\portal_comment
        arguments:
            - '@vinabb.web.entities.portal_comment'
    vinabb.web.operators.bb_category:
        class: vinabb\web\operators\bb_category
        arguments:
            - '@vinabb.web.entities.bb_category'
    vinabb.web.operators.bb_item:
        class: vinabb\web\operators\bb_item
        arguments:
            - '@vinabb.web.entities.bb_item'
    vinabb.web.operators.bb_author:
        class: vinabb\web\operators\bb_author
        arguments:
            - '@vinabb.web.entities.bb_author'
    vinabb.web.operators.page:
        class: vinabb\web\operators\page
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.entities.page'
            - '%vinabb.web.tables.pages%'
    vinabb.web.operators.menu:
        class: vinabb\web\operators\menu
        arguments:
            - '@vinabb.web.entities.menu'
            - '@vinabb.web.operators.nestedset_menus'
    vinabb.web.operators.headline:
        class: vinabb\web\operators\headline
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.entities.headline'
            - '%vinabb.web.tables.headlines%'
