services:
    vinabb.web.constants:
        class: vinabb\web\includes\constants
    vinabb.web.cache:
        class: vinabb\web\controllers\cache\service
        arguments:
            - '@cache.driver'
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
        calls:
            - [set_driver, ['@cache.driver']]
    vinabb.web.pagination:
        class: vinabb\web\controllers\pagination
        arguments:
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
    vinabb.web.helper:
        class: vinabb\web\controllers\helper
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '@file_downloader'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
    vinabb.web.helper.event:
        class: vinabb\web\events\helper\helper
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.helper.entity:
        class: vinabb\web\entities\helper\helper
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.helper.portal:
        class: vinabb\web\controllers\portal\helper\helper
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@notification_manager'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '@path_helper'
            - '%core.root_path%'
    vinabb.web.helper.setting_tasks:
        class: vinabb\web\controllers\acp\helper\setting_tasks
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@user'
