services:
    vinabb.web.user:
        class: vinabb\web\controllers\user\user
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@vinabb.web.pagination'
            - '@profilefields.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.user.profile:
        class: vinabb\web\controllers\user\profile
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@profilefields.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
    vinabb.web.user.contact:
        class: vinabb\web\controllers\user\contact
        arguments:
            - '@language'
            - '@message.form.admin'
            - '@request'
            - '@template'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.user.messenger:
        class: vinabb\web\controllers\user\messenger
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.user.email:
        class: vinabb\web\controllers\user\email
        arguments:
            - '@language'
            - '@message.form.topic'
            - '@message.form.user'
            - '@request'
            - '@template'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.user.team:
        class: vinabb\web\controllers\user\team
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.user.livesearch:
        class: vinabb\web\controllers\user\livesearch
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
    vinabb.web.user.online:
        class: vinabb\web\controllers\user\online
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
    vinabb.web.ucp:
        class: vinabb\web\controllers\ucp
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.mcp:
        class: vinabb\web\controllers\mcp
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board:
        class: vinabb\web\controllers\board\board
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.forum:
        class: vinabb\web\controllers\board\forum
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@cron.manager'
            - '@dbal.conn'
            - '@language'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.topic:
        class: vinabb\web\controllers\board\topic
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@language'
            - '@vinabb.web.pagination'
            - '@profilefields.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.post:
        class: vinabb\web\controllers\board\post
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@content.visibility'
            - '@cron.manager'
            - '@dbal.conn'
            - '@language'
            - '@notification_manager'
            - '@vinabb.web.pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.posting:
        class: vinabb\web\controllers\board\posting
        arguments:
            - '@auth'
            - '@cache'
            - '@captcha.factory'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@plupload'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.board.search:
        class: vinabb\web\controllers\board\search
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
