services:
    # phpBB
    vinabb.web.entities.language:
        class: vinabb\web\entities\language
        shared: false
        arguments:
            - '@dbal.conn'
    vinabb.web.entities.group:
        class: vinabb\web\entities\group
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.user:
        class: vinabb\web\entities\user
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.forum:
        class: vinabb\web\entities\forum
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.topic:
        class: vinabb\web\entities\topic
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.post:
        class: vinabb\web\entities\post
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.post_icon:
        class: vinabb\web\entities\post_icon
        shared: false
        arguments:
            - '@dbal.conn'
    vinabb.web.entities.smiley:
        class: vinabb\web\entities\smiley
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
    vinabb.web.entities.rank:
        class: vinabb\web\entities\rank
        shared: false
        arguments:
            - '@dbal.conn'
    # VinaBB
    vinabb.web.entities.portal_category:
        class: vinabb\web\entities\portal_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.portal_article:
        class: vinabb\web\entities\portal_article
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.portal_articles%'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.entities.portal_comment:
        class: vinabb\web\entities\portal_comment
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.portal_comments%'
            - '%vinabb.web.tables.portal_articles%'
    vinabb.web.entities.bb_category:
        class: vinabb\web\entities\bb_category
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.bb_categories%'
    vinabb.web.entities.bb_item:
        class: vinabb\web\entities\bb_item
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.bb_items%'
            - '%vinabb.web.tables.bb_categories%'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.entities.bb_author:
        class: vinabb\web\entities\bb_author
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.entities.page:
        class: vinabb\web\entities\page
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.pages%'
    vinabb.web.entities.menu:
        class: vinabb\web\entities\menu
        shared: false
        arguments:
            - '@dbal.conn'
            - '%vinabb.web.tables.menus%'
    vinabb.web.entities.headline:
        class: vinabb\web\entities\headline
        shared: false
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.helper.entity'
            - '%vinabb.web.tables.headlines%'
