services:
    vinabb.web.acp.pages:
        class: vinabb\web\controllers\acp\pages
        arguments:
            - '@cache'
            - '@vinabb.web.entities.page'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.page'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
