services:
    # phpBB
    vinabb.web.operators.language:
        class: vinabb\web\operators\language
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.group:
        class: vinabb\web\operators\group
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.team:
        class: vinabb\web\operators\team
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.user:
        class: vinabb\web\operators\user
        arguments:
            - '@auth'
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.forum:
        class: vinabb\web\operators\forum
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.topic:
        class: vinabb\web\operators\topic
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.poll_option:
        class: vinabb\web\operators\poll_option
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.post:
        class: vinabb\web\operators\post
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.draft:
        class: vinabb\web\operators\draft
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.attachment:
        class: vinabb\web\operators\attachment
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.post_icon:
        class: vinabb\web\operators\post_icon
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.smiley:
        class: vinabb\web\operators\smiley
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.rank:
        class: vinabb\web\operators\rank
        arguments:
            - '@service_container'
            - '@dbal.conn'
    vinabb.web.operators.censor_word:
        class: vinabb\web\operators\censor_word
        arguments:
            - '@service_container'
            - '@dbal.conn'
    # VinaBB
    vinabb.web.operators.nestedset_portal_categories:
        class: vinabb\web\operators\nestedset_portal_categories
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.table_lock.portal_categories'
            - '%vinabb.web.tables.portal_categories%'
    vinabb.web.operators.nestedset_menus:
        class: vinabb\web\operators\nestedset_menus
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.table_lock.menus'
            - '%vinabb.web.tables.menus%'
    vinabb.web.operators.portal_category:
        class: vinabb\web\operators\portal_category
        arguments:
            - '@service_container'
            - '@vinabb.web.operators.nestedset_portal_categories'
    vinabb.web.operators.portal_article:
        class: vinabb\web\operators\portal_article
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_articles%'
    vinabb.web.operators.portal_comment:
        class: vinabb\web\operators\portal_comment
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.web.tables.portal_comments%'
    vinabb.web.operators.bb_category:
        class: vinabb\web\operators\bb_category
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@vinabb.web.table_lock.bb_categories'
            - '%vinabb.web.tables.bb_categories%'
    vinabb.web.operators.bb_item:
        class: vinabb\web\operators\bb_item
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_items%'
    vinabb.web.operators.bb_author:
        class: vinabb\web\operators\bb_author
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.web.tables.bb_authors%'
    vinabb.web.operators.page:
        class: vinabb\web\operators\page
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '%vinabb.web.tables.pages%'
    vinabb.web.operators.menu:
        class: vinabb\web\operators\menu
        arguments:
            - '@service_container'
            - '@vinabb.web.operators.nestedset_menus'
    vinabb.web.operators.headline:
        class: vinabb\web\operators\headline
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@vinabb.web.table_lock.headlines'
            - '%vinabb.web.tables.headlines%'
