services:
    vinabb.web.acp.settings:
        class: vinabb\web\controllers\acp\settings
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@config_text'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@vinabb.web.helper.setting_tasks'
    vinabb.web.acp.portal_categories:
        class: vinabb\web\controllers\acp\portal_categories
        arguments:
            - '@vinabb.web.operators.portal_article'
            - '@vinabb.web.cache'
            - '@service_container'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.portal_category'
            - '@request'
            - '@template'
            - '@user'
            - '@vinabb.web.helper'
    vinabb.web.acp.portal_articles:
        class: vinabb\web\controllers\acp\portal_articles
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@ext.manager'
            - '@filesystem'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.portal_article'
            - '@request'
            - '@template'
            - '@files.upload'
            - '@user'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.acp.portal_comments:
        class: vinabb\web\controllers\acp\portal_comments
        arguments:
            - '@auth'
            - '@service_container'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.portal_comment'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.acp.bb_categories:
        class: vinabb\web\controllers\acp\bb_categories
        arguments:
            - '@vinabb.web.cache'
            - '@service_container'
            - '@vinabb.web.operators.bb_item'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.bb_category'
            - '@request'
            - '@template'
            - '@user'
            - '@vinabb.web.helper'
    vinabb.web.acp.bb_items:
        class: vinabb\web\controllers\acp\bb_items
        arguments:
            - '@vinabb.web.acp.bb_item_versions'
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.bb_item'
            - '@request'
            - '@template'
            - '@user'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
    vinabb.web.acp.bb_item_versions:
        class: vinabb\web\controllers\acp\bb_item_versions
        arguments:
            - '@config'
            - '@service_container'
            - '@ext.manager'
            - '@filesystem'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.bb_item_version'
            - '@request'
            - '@template'
            - '@files.upload'
            - '@user'
            - '@vinabb.web.helper'
    vinabb.web.acp.bb_authors:
        class: vinabb\web\controllers\acp\bb_authors
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@vinabb.web.operators.bb_item'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.bb_author'
            - '@request'
            - '@template'
            - '@user'
    vinabb.web.acp.pages:
        class: vinabb\web\controllers\acp\pages
        arguments:
            - '@vinabb.web.cache'
            - '@service_container'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.page'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.acp.menus:
        class: vinabb\web\controllers\acp\menus
        arguments:
            - '@vinabb.web.cache'
            - '@service_container'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.menu'
            - '@request'
            - '@template'
            - '@user'
            - '@vinabb.web.helper'
            - '@group_helper'
    vinabb.web.acp.headlines:
        class: vinabb\web\controllers\acp\headlines
        arguments:
            - '@vinabb.web.cache'
            - '@config'
            - '@service_container'
            - '@ext.manager'
            - '@filesystem'
            - '@language'
            - '@log'
            - '@vinabb.web.operators.headline'
            - '@request'
            - '@template'
            - '@files.upload'
            - '@user'
            - '@vinabb.web.helper'
