services:
    vinabb.web.listener.helper:
        class: vinabb\web\events\helper
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
    vinabb.web.listener:
        class: vinabb\web\events\listener
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@vinabb.web.cache'
            - '@config'
            - '@ext.manager'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.listener.helper'
            - '@vinabb.web.helper'
            - '@path_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
