imports:
    - { resource: tables.yml }
    - { resource: services_decorates.yml }
    - { resource: services_common.yml }
    - { resource: services_phpbb.yml }
    - { resource: services_embed.yml }
    - { resource: services_entities.yml }
    - { resource: services_operators.yml }
    - { resource: services_table_lock.yml }
    - { resource: services_acp_controllers.yml }
    - { resource: services_controllers.yml }
    - { resource: services_listeners.yml }
