services:
    vinabb.web.listener:
        class: vinabb\web\events\common
        arguments:
            - '@auth'
            - '@vinabb.web.cache'
            - '@config'
            - '@ext.manager'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@vinabb.web.helper.event'
            - '@path_helper'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    vinabb.web.listener.acp:
        class: vinabb\web\events\acp
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.cache'
            - '@config'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
    vinabb.web.listener.seo:
        class: vinabb\web\events\seo
        arguments:
            - '@dbal.conn'
            - '@vinabb.web.cache'
            - '@vinabb.web.helper'
        tags:
            - { name: event.listener }
    vinabb.web.listener.text_formatter:
        class: vinabb\web\events\text_formatter
        arguments:
            - '@template'
            - '@vinabb.web.helper.event'
        tags:
            - { name: event.listener }
