parameters:
    vinabb.web.tables.bb_authors: '%core.table_prefix%bb_authors'
    vinabb.web.tables.bb_categories: '%core.table_prefix%bb_categories'
    vinabb.web.tables.bb_items: '%core.table_prefix%bb_items'
    vinabb.web.tables.bb_item_versions: '%core.table_prefix%bb_item_versions'
    vinabb.web.tables.bb_rates: '%core.table_prefix%bb_rates'
    vinabb.web.tables.headlines: '%core.table_prefix%headlines'
    vinabb.web.tables.menus: '%core.table_prefix%menus'
    vinabb.web.tables.pages: '%core.table_prefix%pages'
    vinabb.web.tables.portal_articles: '%core.table_prefix%portal_articles'
    vinabb.web.tables.portal_categories: '%core.table_prefix%portal_categories'
    vinabb.web.tables.portal_comments: '%core.table_prefix%portal_comments'
    vinabb.web.tables.portal_rates: '%core.table_prefix%portal_rates'
