vinabb_web_user_routing:
    resource: routing_user.yml
    prefix: /user
vinabb_web_ucp_route:
    path: /ucp/{id}/{mode}
    defaults:
        _controller: vinabb.web.ucp:main
        id: 'front'
        mode: ''
    requirements:
        id: '[a-z0-9-_]*'
        mode: '([a-z0-9-_]*)([\/]{0,1})'
vinabb_web_board_route:
    path: /{board}
    defaults:
        _controller: vinabb.web.board:index
        board: 'board'
    requirements:
        board: '(board|board\/)'
vinabb_web_board_routing:
    resource: routing_board.yml
    prefix: /board
vinabb_web_embed_routing:
    resource: routing_embed.yml
    prefix: /embed
vinabb_web_search_route:
    path: /search/{mode}
    defaults:
        _controller: vinabb.web.search:index
        mode: ''
    requirements:
        mode: '[a-z]+'
vinabb_web_online_route:
    path: /online/{mode}
    defaults:
        _controller: vinabb.web.online:index
        mode: ''
    requirements:
        mode: '(|whois|whois\/)'
vinabb_web_portal_route:
    path: /news
    defaults:
        _controller: vinabb.web.portal:index
vinabb_web_bb_route:
    path: /{bb}
    defaults:
        _controller: vinabb.web.bb:index
    requirements:
        bb: '(bb|bb\/)'
vinabb_web_bb_routing:
    resource: routing_bb.yml
    prefix: /bb
