vinabb_web_board_forum_route:
    path: /forum/{forum_id}
    defaults:
        _controller: vinabb.web.board:forum
    requirements:
        forum_id: '\d*'
vinabb_web_board_topic_route:
    path: /topic/{topic_id}
    defaults:
        _controller: vinabb.web.board:topic
    requirements:
        topic_id: '\d+'
vinabb_web_board_post_route:
    path: /post/{post_id}
    defaults:
        _controller: vinabb.web.board:post
    requirements:
        post_id: '\d+'
