vinabb_web_user_route:
    path: /user/{username}
    defaults: { _controller: vinabb.web.user:info }
vinabb_web_bb_route:
    path: /{bb}
    defaults: { _controller: vinabb.web.bb:index }
    requirements:
        bb: (bb|bb\/)
vinabb_web_bb_routing:
    resource: routing_bb.yml
    prefix: /bb
