vinabb_web_user_routing:
    resource: routing_user.yml
    prefix: /user
vinabb_web_board_route:
    path: /{board}
    defaults: { _controller: vinabb.web.board:index }
    requirements:
        board: '(board|board\/)'
vinabb_web_board_routing:
    resource: routing_board.yml
    prefix: /board
vinabb_web_embed_routing:
    resource: routing_embed.yml
    prefix: /embed
vinabb_web_portal_route:
    path: /news
    defaults: { _controller: vinabb.web.portal:index }
vinabb_web_bb_route:
    path: /{bb}
    defaults: { _controller: vinabb.web.bb:index }
    requirements:
        bb: '(bb|bb\/)'
vinabb_web_bb_routing:
    resource: routing_bb.yml
    prefix: /bb
